.TH gearmand 8 2009-05-31 "Gearman" "Gearman"
.SH NAME
gearmand \- Gearman job server
.SH SYNOPSIS
.B gearmand
[\fIOPTION\fR]...
.SH DESCRIPTION
This is the C implementation of the Gearman job server. Run 'gearmand \-\-help' for usage details. Better documentation coming soon. :)
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
